name: CI Go + Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build do código Go
      run: go build -o app

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build da imagem Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/site-monitor-go:latest .

    - name: Push para o Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/site-monitor-go:latest
